[project]
name = "minecraft-clicker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flet[all]>=0.28.3",
    "keyboard>=0.13.5",
    "pyautogui>=0.9.54",
]
